### ISSUE TITLE
TODO list (LONG ISSUE)

### ISSUE THREAD

**Issue by effdrums** [effdrums/python_projects#1]
**EVENTS**
- [ ] Create enum class or event class for events

**FLOW**
- [ ] Change player turn
 

**TANK FLOW**
- [ ] Implement Functions on update

**TANK SPRITES**
- [ ] Create class TankObject to add sprites to a single tank
- [x] Create healthBar
- [x] Create fuelBar
- [x] Create bombBar
- [ ] Create shieldBar
- [ ] Create optionBar

**TANK ANIMATIONS**
- [x] TankShake
- [x] Slow down tank shake
 
**GENREAL**
- [ ] Refactor main separate in functions
- [x] Add to bars a draw(screen) function then the call should be like: myBar.draw(screen) instead of myBar.getGrou().draw(screen)
